version: "3.9"

services:
  frontend:
    build:
      context: ./frontend/
      args:
        API_URL: http://0.0.0.0:8000
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
